language: python
python:
- 3.7
install:
- pip install -r requirements.txt
before_script:
- psql -c "CREATE DATABASE boardgamestore;" -U postgres
- psql -c "CREATE ROLE postgres SUPERUSER LOGIN CREATEDB;" -U postgres
script:
- python manage.py test
services:
- postgresql
env:
  global:
  - secure: msPeircsz61L2Hw9Zgp6jzDnaevcxVT1gIsCOP54Ecogso6Nkn8tX1tiXHcmP1j/F5hVfFSLCTdl1defpZGnLMunNvCeToXsvR/9Zvof32doA1fO0RxO6yLqLPPz+ZfTXcQUYK/jY/nua47Ymld39ah018+FvJGPAK0VI7em4ponGR7hjXCc0L4dwRq3t+d4PwIqjOHbTpH+egSc/GU7phc7jRUnow2BUKJBbUJadVqMaTgMdbbY/XTzLXah2h67kmlp+j0JHHQxEwIn0aObbOuXeUZsQLPFGuJ+vcRWtBZoMWXyh8d/2vQZDxqRU5PM08q5m3G3lGyDrc4WwEFmowryZ0PNsPYRVAzUsfEIn2a2z1lIPYWMLl0sHyGJ/4sLhO6v3MbtZAO9dWD/862XpjNlRPvC67WEwrXo57U6EGcDwm2/dnjO82GehDXolcuES+PHyL9a/U/qp0b+iatP6T25CzbG9i7zwwrbx1DEwVEtkrzPL0RGWR0Bo1UFQng5FFQDFR3xNKmS62+tNChP+qx/D6leItXfaYZb0N2HLGwq6EwfNjXgvcQjy0+453Kc/Q09rwaX1DLVBzzCVsney6vu+c1d8G6Qf7saX+MqRJZEbjgoy5YykAan5IlJAgVUiMoUAh82URhDRAFgqtGjXEhdA7Zl8vFBzQBwL6PlvnU=
  - secure: R2PZQaRW4baqEbZmESqGcxS8d9ni+h6agT3ynwaxLkcfem+ixkFRn8xb1WUivPHGDPrT4j+7CnxdrshZVa82ThhTMDvQA2OIa0GQiH90yeqrF5QKFxwM+XYmanfRK5tI4Peyh7+5++ejKjeDwQwxr31J4DgIZ/QtfNZojvKVobEn2H4rMX/HnxnOwxmkWOZSN/45HYaWSE217oDxBZChPJ01kxPVlc5qQNv9VqKjUeq3KzSJvbeSWT1oFgZ8AtSEXoYp8Dr9nrbo1iXfq+QRY4w3o8ud/qnnwuRg0lYv0EQVwixiQ5yFTLAiqAKx3C19WpZzfvTVPQvNbWUXgzY5InPIhnHxbTCZ65KchWRsvtgQcncbHs9Yj8uINqWxzAT4dgOyG/0JOFrIPGN5IDwrvQbqJ9xJwdY5kfQwQ3KlHcPqf2M4duhqne4IfoJiiAGvCvX+weE/FIcnqwe293pLkLpYSzXx9lTRTneuYno482kwRBMdxJ0fiyopEBWECq3WzLC6T4+j3UdWx8wpedQ1wWN3QRypJWw8jr1xV0N37LGmRE3B8wnNzzNRYftwekIHZpfnCOmPvdFC7pvsBznWmZ2yARtBDQ+ZaLKwilnQZ9O+IWWIxa7FviktqGOtIkNJiTGF1/ptkF1/RDdvI/5JIjvZJmpgW0vlTvxJGaxd8Yc=
