# Generated by Django 2.2.6 on 2020-01-31 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20200131_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='perecent',
            new_name='percent',
        ),
    ]
