# Generated by Django 2.2.6 on 2020-01-31 05:33

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20200131_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=pyuploadcare.dj.models.ImageField(null=True),
        ),
    ]
