# Generated by Django 2.2.6 on 2020-02-15 08:15

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='inside_box',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='game',
            name='stock_left',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
