# Generated by Django 2.2.6 on 2020-02-17 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_auto_20200217_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='stock_left',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
