# Generated by Django 2.2.6 on 2020-02-25 08:48

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20200218_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=pyuploadcare.dj.models.ImageField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='inside_box',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
