# Generated by Django 2.2.6 on 2020-02-28 16:13

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_game_homepage_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
    ]
