# Generated by Django 2.2.6 on 2020-02-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20200228_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image_text',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
