# Generated by Django 2.2.6 on 2020-02-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_game_image_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='image_text',
        ),
    ]
