# Generated by Django 2.2.6 on 2020-03-01 00:09

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_remove_game_image_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=pyuploadcare.dj.models.ImageField(null=True),
        ),
    ]
